development:
  adapter: postgresql
  database: wavepool_development
  pool: 25

test:
  adapter: postgresql
  database: wavepool_test
  pool: 5

production:
  adapter: postgresql
  database: wavepool_production
  pool: 25
