development:
  adapter: postgresql
  database: whirlwind_development
  pool: 25

test:
  adapter: postgresql
  database: whirlwind_test
  pool: 5

production:
  adapter: postgresql
  database: whirlwind_production
  pool: 25
